if(typeof goog!="undefined"&&typeof goog.provide=="function")MochiKit.Base_ext={};MochiKit.Base.module(MochiKit,"Base_ext","1.5",["Base"]);MochiKit.Base._arg_placeholder=function(a){this.index=a};
var _1=new MochiKit.Base._arg_placeholder(0),_2=new MochiKit.Base._arg_placeholder(1),_3=new MochiKit.Base._arg_placeholder(2),_4=new MochiKit.Base._arg_placeholder(3),_5=new MochiKit.Base._arg_placeholder(4),_6=new MochiKit.Base._arg_placeholder(5),_7=new MochiKit.Base._arg_placeholder(6),_8=new MochiKit.Base._arg_placeholder(7),_9=new MochiKit.Base._arg_placeholder(8),_10=new MochiKit.Base._arg_placeholder(9);
MochiKit.Base._rebind_preargs=function(a,b,c){c=c||{};for(var d=0;d<a.length;++d){var e=a[d];if(e instanceof MochiKit.Base._arg_placeholder){if(e.index<b.length){a[d]=b[e.index];c[e.index]=e.index}}else typeof e=="function"&&typeof e.im_func=="function"&&MochiKit.Base._rebind_preargs(e.im_preargs,b,c)}return c};
MochiKit.Base.bind2=function(a,b){if(typeof a=="string")a=b[a];var c=a.im_func,d=a.im_preargs,e=a.im_self,f=MochiKit.Base;if(typeof a=="function"&&typeof a.apply=="undefined")a=f._wrapDumbFunction(a);if(typeof c!="function")c=a;if(typeof b!="undefined")e=b;d=typeof d=="undefined"?[]:d.slice();var g=Array.prototype.slice.call(arguments,b instanceof f._arg_placeholder?1:2),h=MochiKit.Base._rebind_preargs(d,g),i;for(i in h)g.splice(h[i],1);f.extend(d,g);g=function(){var j=arguments.callee,k=j.im_self;
k||(k=this);var l=[];if(j.im_preargs.length>0){for(var m=0,o=0;o<j.im_preargs.length;++o){var p=j.im_preargs[o];if(p instanceof f._arg_placeholder){m=Math.max(m,p.index+1);p=arguments[p.index]}else if(typeof p=="function"&&typeof p.im_func=="function")p=p.apply(k,arguments);l.push(p)}for(;m<arguments.length;++m)l.push(arguments[m])}else l=arguments;if(k instanceof f._arg_placeholder)k=arguments[k.index];return j.im_func.apply(k,l)};g.im_self=e;g.im_func=c;g.im_preargs=d;if(typeof c.NAME=="string")g.NAME=
"bind2("+c.NAME+",...)";return g};MochiKit.Base.partial2=function(a){var b=MochiKit.Base;return b.bind2.apply(this,b.extend([a,undefined],arguments,1))};MochiKit.Base.method2=function(a,b){var c=MochiKit.Base;return c.bind2.apply(this,c.extend([b,a],arguments,2))};MochiKit.Base.bindLate2=function(a){var b=MochiKit.Base,c=arguments;if(typeof a==="string")c=b.extend([b.forwardCall(a)],arguments,1);return b.bind2.apply(this,c)};
MochiKit.Base.isBoundFunction=function(a){return typeof a=="function"&&typeof a.im_func=="function"};MochiKit.Base.protect=function(a){return function(){return a.apply(this,arguments)}};MochiKit.Base.apply=function(a){var b=MochiKit.Base.extend([],arguments,1);return a.apply(this,b)};
MochiKit.Base.partition=function(a,b,c,d,e){function f(h,i){var j=a[h];a[h]=a[i];a[i]=j}b=b||MochiKit.Base.operator.cle;c=c||0;d=d||a.length-1;e=e||c+Math.floor((d-c)/2);var g=a[e];f(e,d);for(e=c;c<=d;++c)if(b(a[c],g)){f(c,e);++e}f(e,d);return e};MochiKit.Base.countValue=function(a,b,c){c=c||MochiKit.Base.operator.ceq;var d=0;MochiKit.Iter.forEach(a,function(e){c(e,b)&&++d});return d};MochiKit.Base.negateComparator=function(a){return function(){return-1*a.apply(this,arguments)}};
MochiKit.Base_ext.__new__=function(){};MochiKit.Base_ext.__new__();MochiKit.Base._exportSymbols(this,MochiKit.Base);if(typeof goog!="undefined"&&typeof goog.provide=="function")MochiKit.Bisect={};MochiKit.Base.module(MochiKit,"Bisect","1.5",["Base"]);MochiKit.Bisect.bisectRight=function(a,b,c,d){c=c||0;for(d=d||a.length;c<d;){var e=Math.floor((c+d)/2);if(MochiKit.Base.compare(b,a[e])<0)d=e;else c=e+1}return c};MochiKit.Bisect.insortRight=function(a,b,c,d){c=MochiKit.Bisect.bisectRight(a,b,c,d);a.splice(c,0,b);return a};
MochiKit.Bisect.bisectLeft=function(a,b,c,d){c=c||0;for(d=d||a.length;c<d;){var e=Math.floor((c+d)/2);if(MochiKit.Base.compare(a[e],b)<0)c=e+1;else d=e}return c};MochiKit.Bisect.insortLeft=function(a,b,c,d){c=MochiKit.Bisect.bisectLeft(a,b,c,d);a.splice(c,0,b);return a};MochiKit.Bisect.bisect=MochiKit.Bisect.bisectRight;MochiKit.Bisect.insort=MochiKit.Bisect.insortRight;MochiKit.Bisect.__new__=function(){};MochiKit.Bisect.__new__();MochiKit.Base._exportSymbols(this,MochiKit.Bisect);if(typeof goog!="undefined"&&typeof goog.provide=="function")MochiKit.HeapQ={};MochiKit.Base.module(MochiKit,"HeapQ","1.5",["Base","Iter"]);MochiKit.HeapQ.heapify=function(a,b){b=b||MochiKit.Base.operator.clt;for(var c=Math.floor(a.length/2)-1;c>=0;--c)MochiKit.HeapQ._siftup(a,c,b);return a};MochiKit.HeapQ._siftdown=function(a,b,c,d){d=d||MochiKit.Base.operator.clt;for(var e=a[c];c>b;){var f=c-1>>1,g=a[f];if(d(e,g)){a[c]=g;c=f}else break}a[c]=e};
MochiKit.HeapQ._siftup=function(a,b,c){c=c||MochiKit.Base.operator.clt;for(var d=a.length,e=b,f=a[b],g=2*b+1;g<d;){var h=g+1;if(h<d&&!c(a[g],a[h]))g=h;a[b]=a[g];b=g;g=2*b+1}a[b]=f;MochiKit.HeapQ._siftdown(a,e,b,c)};MochiKit.HeapQ.heapPush=function(a,b,c){c=c||MochiKit.Base.operator.clt;a.push(b);MochiKit.HeapQ._siftdown(a,0,a.length-1,c)};MochiKit.HeapQ.heapPop=function(a,b){b=b||MochiKit.Base.operator.clt;var c=a.pop(),d;if(a.length>0){d=a[0];a[0]=c;MochiKit.HeapQ._siftup(a,0,b)}else d=c;return d};
MochiKit.HeapQ.heapReplace=function(a,b,c){c=c||MochiKit.Base.operator.clt;var d=a[0];a[0]=b;MochiKit.HeapQ._siftup(a,0,c);return d};MochiKit.HeapQ.heapPushPop=function(a,b,c){c=c||MochiKit.Base.operator.clt;if(a.length>0&&c(a[0],b)){var d=a[0];a[0]=b;b=d;MochiKit.HeapQ._siftup(a,0,c)}return b};
MochiKit.HeapQ.imergeSorted=function(a,b){var c=MochiKit,d=c.Iter;b=b||c.Base.operator.clt;var e=function(g,h){return b(g[0],h[0])},f=[];d.forEach(d.izip(d.count(),d.imap(d.iter,a)),function(g){var h=g[0];g=g[1];try{var i=g.next;f.push([i(),h,i])}catch(j){if(j!=d.StopIteration)throw j;}});c.HeapQ.heapify(f,e);return{repr:function(){return"imergeSorted(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){for(;;){if(f.length==0)throw d.StopIteration;var g=f[0],h=g[0],i=g[2];try{g[0]=i();
c.HeapQ.heapReplace(f,g,e)}catch(j){if(j!=d.StopIteration)throw j;c.HeapQ.heapPop(f,e)}return h}}}};MochiKit.HeapQ.heapIter=function(a,b){b=b||MochiKit.Base.operator.clt;return{next:function(){if(a.length==0)throw MochiKit.Iter.StopIteration;return MochiKit.HeapQ.heapPop(a,b)}}};
MochiKit.HeapQ.nLargest=function(a,b,c){var d=MochiKit,e=d.Iter;c=c||d.Base.operator.clt;b=e.iter(b);var f=e.list(e.islice(b,a));if(f.length==0)return f;d.HeapQ.heapify(f,c);e.forEach(b,function(g){d.HeapQ.heapPushPop(f,g,c)});f.sort(function(g,h){return-1*d.Base.compare(g,h)});return f};MochiKit.HeapQ.nSmallest=function(a,b,c){var d=MochiKit,e=d.Iter;c=c||d.Base.operator.clt;b=e.list(b);d.HeapQ.heapify(b,c);return d.Base.map(d.Base.partial(d.HeapQ.heapPop,b,c),e.range(Math.min(a,b.length)))};
MochiKit.HeapQ.isHeap=function(a,b){b=b||MochiKit.Base.operator.cle;for(var c=1;c<a.length;++c)if(!b(a[c-1>>1],a[c]))return false;return true};MochiKit.HeapQ.heapSort=function(a,b){var c=MochiKit,d=c.Iter.list(a);c.HeapQ.heapify(d,b);return c.Base.map(c.Base.partial(c.HeapQ.heapPop,d,b),c.Iter.range(d.length))};MochiKit.HeapQ.__new__=function(){};MochiKit.HeapQ.__new__();MochiKit.Base._exportSymbols(this,MochiKit.HeapQ);if(typeof goog!="undefined"&&typeof goog.provide=="function")MochiKit.Iter_ext={};MochiKit.Base.module(MochiKit,"Iter_ext","1.5",["Base","Iter"]);MochiKit.Iter.treePreOrder=function(a,b){var c=[a];return{repr:function(){return"treePreOrder(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){if(c.length==0)throw MochiKit.Iter.StopIteration;var d=c.pop();MochiKit.Iter.iextend(c,b(d));return d}}};
MochiKit.Iter.treeLevelOrder=function(a,b){var c=[a];return{repr:function(){return"treeLevelOrder(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){if(c.length==0)throw MochiKit.Iter.StopIteration;var d=c.shift();MochiKit.Iter.iextend(c,b(d));return d}}};
MochiKit.Iter.treePostOrder=function(a,b){var c=[[a,false]];return{repr:function(){return"treePostOrder(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){for(;;){if(c.length==0)throw MochiKit.Iter.StopIteration;var d=c.pop();if(d[1])return d[0];d[1]=true;c.push(d);MochiKit.Iter.iextend(c,MochiKit.Iter.imap(function(e){return[e,false]},b(d[0])))}}}};
MochiKit.Iter.pairView=function(a,b){b=b||false;var c=MochiKit.Iter.iter(a);try{var d=c.next()}catch(e){if(e!=MochiKit.Iter.StopIteration)throw e;return MochiKit.Iter.EmptyIter}if(b)c=MochiKit.Iter.chain(c,[d]);return{repr:function(){return"pairView(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){var f=c.next(),g=[d,f];d=f;return g}}};
MochiKit.Iter.windowView=function(a,b,c){b=b||2;c=c||1;var d=MochiKit.Iter.iter(a),e=[];return{repr:function(){return"windowView(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){if(e.length<b)for(;e.length<b;)e.push(d.next());else for(var f=0;f<c;++f){e.shift();e.push(d.next())}return e.slice()}}};MochiKit.Iter.filterMap=function(a,b,c){return MochiKit.Iter.ifilter(c||function(d){return typeof d!=="undefined"&&d!==null},MochiKit.Iter.imap(a,b))};
MochiKit.Iter.iflattenArray=function(a){var b=[a];return{repr:function(){return"iflattenArray(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){for(;;){if(b.length==0)throw MochiKit.Iter.StopIteration;var c=b.shift();if(c instanceof Array)Array.prototype.splice.apply(b,[0,0].concat(c));else return c}}}};
MochiKit.Iter.chainFromIter=function(a,b){b=b||MochiKit.Iter.iter;var c=MochiKit.Iter.iter(a),d=null;return{repr:function(){return"chainFromIter(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){if(d==null)d=MochiKit.Iter.iter(b(c.next()));for(;;)try{return d.next()}catch(e){if(e!=MochiKit.Iter.StopIteration)throw e;d=MochiKit.Iter.iter(b(c.next()))}}}};
MochiKit.Iter.uniqueView=function(a,b){b=b||MochiKit.Base.operator.ceq;var c=MochiKit.Iter.iter(a),d=true,e;return{repr:function(){return"uniqueView(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){if(d){d=false;return e=c.next()}for(var f=c.next();b(e,f);)f=c.next();return e=f}}};
MochiKit.Iter.iproduct=function(a,b){var c=MochiKit.Iter.iter(a),d=null,e,f;return{repr:function(){return"iproduct(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){for(;;){if(d==null){e=c.next();d=MochiKit.Iter.iter(b)}try{f=d.next();return[e,f]}catch(g){if(g!=MochiKit.Iter.StopIteration)throw g;d=null}}}}};MochiKit.Iter.enumerate=function(a,b){return MochiKit.Iter.izip(MochiKit.Iter.count(b),a)};MochiKit.Iter.breakIt=function(){throw MochiKit.Iter.StopIteration;};
MochiKit.Iter.EmptyIter={repr:function(){return"EmptyIter"},toString:MochiKit.Base.forwardCall("repr"),next:MochiKit.Iter.breakIt};MochiKit.Iter.generateN=function(a,b){return MochiKit.Iter.imap(function(){return a()},MochiKit.Iter.range(b))};
MochiKit.Iter.izipLongest=function(a,b){b=b||null;a=MochiKit.Base.map(MochiKit.Iter.iter,a);var c=a.length;return{repr:function(){return"izipLongest(...)"},toString:MochiKit.Base.forwardCall("repr"),next:function(){for(var d=Array(a.length),e=0;e<a.length;++e)try{d[e]=a[e].next()}catch(f){if(f!=MochiKit.Iter.StopIteration)throw f;a[e]=MochiKit.Iter.repeat(b);d[e]=b;--c}if(c==0)throw MochiKit.Iter.StopIteration;return d}}};MochiKit.Iter.any=function(){return MochiKit.Iter.some.apply(this,arguments)};
MochiKit.Iter.all=function(){return MochiKit.Iter.every.apply(this,arguments)};MochiKit.Iter.starmap=function(){return MochiKit.Iter.applymap.apply(this,arguments)};MochiKit.Iter.advance=function(a,b){for(;b-- >0;)a.next();return a};MochiKit.Iter.isSorted=function(a,b){return MochiKit.Iter.every(MochiKit.Iter.windowView(a),b||MochiKit.Base.operator.cle)};MochiKit.Iter.interleave=function(){return MochiKit.Iter.chainFromIter(MochiKit.Iter.izip.apply(this,arguments))};
MochiKit.Iter.remapView=function(a,b){return MochiKit.Iter.imap(MochiKit.Base.partial(MochiKit.Base.operator.getitem,b),a)};MochiKit.Iter.compressIter=function(a,b){return MochiKit.Iter.imap(function(c){return c[0]},MochiKit.Iter.ifilter(function(c){return c[1]?true:false},MochiKit.Iter.izip(a,b)))};
MochiKit.Iter.combinations=function(a,b){var c=MochiKit,d=MochiKit.Iter,e=d.list(a),f=e.length;if(b>f)return MochiKit.Iter.EmptyIter;var g=d.list(d.range(b)),h=true;return{repr:function(){return"combinations(...)"},toString:c.Base.forwardCall("repr"),next:function(){if(h){h=false;return d.list(d.remapView(g,e))}for(;;){for(var i=true,j=b-1;j>=0;--j)if(g[j]!=j+f-b){i=false;break}if(i)throw MochiKit.Iter.StopIteration;g[j]+=1;for(i=j+1;i<b;++i)g[i]=g[i-1]+1;return d.list(d.remapView(g,e))}}}};
MochiKit.Iter.combinationsWithReplacement=function(a,b){var c=MochiKit,d=MochiKit.Iter,e=d.list(a),f=e.length;if(f==0||b==0)return d.EmptyIter;var g=d.list(d.repeat(0,b)),h=true;return{repr:function(){return"combinationsWithReplacement(...)"},toString:c.Base.forwardCall("repr"),next:function(){if(h){h=false;return d.list(d.remapView(g,e))}for(;;){for(var i=true,j=b-1;j>=0;--j)if(g[j]!=f-1){i=false;break}if(i)throw d.StopIteration;g=g.slice(0,j).concat(d.list(d.repeat(g[j]+1,b-j)));return d.list(d.remapView(g,
e))}}}};MochiKit.Iter.repeatSeq=function(a,b){if(b==0)return MochiKit.Iter.EmptyIter;var c=MochiKit.Iter.iter(a);return{next:function(){try{return c.next()}catch(d){if(d!=MochiKit.Iter.StopIteration||--b<=0)throw d;c=MochiKit.Iter.iter(a);return c.next()}}}};
MochiKit.Iter.permutations=function(a,b){var c=MochiKit,d=MochiKit.Iter,e=d.list(a),f=e.length;b=b||f;if(b>f)return d.EmptyIter;var g=d.list(d.range(f)),h=d.list(d.range(f,f-b,-1)),i=true;return{repr:function(){return"permutations(...)"},toString:c.Base.forwardCall("repr"),next:function(){if(i){i=false;return d.list(d.remapView(d.islice(g,0,b),e))}if(f==0)throw d.StopIteration;for(var j=true,k=b-1;k>=0;--k){h[k]-=1;if(h[k]==0){g=g.slice(0,k).concat(g.slice(k+1),g[k]);h[k]=f-k}else{j=g.length-h[k];
var l=g[k];g[k]=g[j];g[j]=l;j=false;break}}if(j)throw d.StopIteration;return d.list(d.remapView(d.islice(g,0,b),e))}}};MochiKit.Iter._Range=function(a,b,c){this.start=a;this.stop=b;this.step=c};MochiKit.Iter._Range.prototype.__iterator__=function(){return new MochiKit.Iter.range(this.start,this.stop,this.step)};
MochiKit.Iter.xrange=function(){var a=0,b=0,c=1;if(arguments.length==1)b=arguments[0];else if(arguments.length==2){a=arguments[0];b=arguments[1]}else if(arguments.length==3){a=arguments[0];b=arguments[1];c=arguments[2]}else throw new TypeError("xrange() takes 1, 2, or 3 arguments!");if(c===0)throw new TypeError("xrange() step must not be 0");return new MochiKit.Iter._Range(a,b,c)};MochiKit.Iter_ext.__new__=function(){};MochiKit.Iter_ext.__new__();MochiKit.Base._exportSymbols(this,MochiKit.Iter);MochiKit.Base.module(MochiKit,"_MersenneTwister19937","1.5",["Base"]);
MochiKit._MersenneTwister19937=function(){function a(g){return g<0?(g^d)+d:g}function b(g,h){return a(g+h&4294967295)}function c(g,h){for(var i=0,j=0;j<32;++j)if(g>>>j&1)i=b(i,a(h<<j));return i}var d=2147483648,e=Array(624),f=625;this.init_genrand=function(g){e[0]=a(g&4294967295);for(f=1;f<624;f++){e[f]=b(c(1812433253,a(e[f-1]^e[f-1]>>>30)),f);e[f]=a(e[f]&4294967295)}};this.init_by_array=function(g,h){var i,j,k;this.init_genrand(19650218);i=1;j=0;for(k=624>h?624:h;k;k--){e[i]=b(b(a(e[i]^c(a(e[i-1]^
e[i-1]>>>30),1664525)),g[j]),j);e[i]=a(e[i]&4294967295);i++;j++;if(i>=624){e[0]=e[623];i=1}if(j>=h)j=0}for(k=623;k;k--){j=e;var l=i,m;m=a(e[i]^c(a(e[i-1]^e[i-1]>>>30),1566083941));var o=i;m=m<o?a(4294967296-(o-m)&4294967295):m-o;j[l]=m;e[i]=a(e[i]&4294967295);i++;if(i>=624){e[0]=e[623];i=1}}e[0]=2147483648};this.genrand_int32=function(){var g,h=[0,2567483615];if(f>=624){var i;f==625&&this.init_genrand(5489);for(i=0;i<227;i++){g=a(e[i]&d|e[i+1]&2147483647);e[i]=a(e[i+397]^g>>>1^h[g&1])}for(;i<623;i++){g=
a(e[i]&d|e[i+1]&2147483647);e[i]=a(e[i+-227]^g>>>1^h[g&1])}g=a(e[623]&d|e[0]&2147483647);e[623]=a(e[396]^g>>>1^h[g&1]);f=0}g=e[f++];g=a(g^g>>>11);g=a(g^g<<7&2636928640);g=a(g^g<<15&4022730752);return g=a(g^g>>>18)};this.genrand_int31=function(){return this.genrand_int32()>>>1};this.genrand_real1=function(){return this.genrand_int32()*(1/4294967295)};this.genrand_real2=function(){return this.genrand_int32()*(1/4294967296)};this.genrand_real3=function(){return(this.genrand_int32()+0.5)*(1/4294967296)};
this.genrand_res53=function(){var g=this.genrand_int32()>>>5,h=this.genrand_int32()>>>6;return(g*67108864+h)*1.1102230246251565E-16};this._getState=function(){return{mt:e.slice(),mti:f}};this._setState=function(g){e=g.mt;f=g.mti}};if(typeof goog!="undefined"&&typeof goog.provide=="function")MochiKit.Random={};MochiKit.Base.module(MochiKit,"Random","1.5",["Base","_MersenneTwister19937"]);MochiKit.Random.seed=function(a){a=typeof a=="number"?a:(new Date).getTime();MochiKit.Random._generator.seed(a)};MochiKit.Random.getState=function(){return MochiKit.Random._generator.getState()};MochiKit.Random.setState=function(a){MochiKit.Random._generator.setState(a)};MochiKit.Random.random=function(){return MochiKit.Random._generator.random()};
MochiKit.Random.randRange=function(a,b,c){var d=MochiKit.Random;if(arguments.length==1){b=a;a=0}c=c||1;var e=b-a;if(c==1&&e>0)return Math.floor(a+Math.floor(d.random()*e));if(c>0)var f=Math.floor((e+c-1)/c);else if(c<0)f=Math.floor((e+c+1)/c);return a+c*Math.floor(d.random()*f)};MochiKit.Random.uniform=function(a,b){return a+(b-a)*MochiKit.Random.random()};MochiKit.Random.shuffle=function(a){for(var b=a.length-1;b>0;--b){var c=Math.floor(MochiKit.Random.random()*(b+1)),d=a[b];a[b]=a[c];a[c]=d}return a};
MochiKit.Random.deal=function(a,b){b=b||MochiKit.Base.operator.identity;for(var c=Array(a),d=0;d<a;++d){var e=Math.floor(MochiKit.Random.random()*(d+1));c[d]=c[e];c[e]=b(d)}return c};MochiKit.Random.choice=function(a){return a[Math.floor(MochiKit.Random.random()*a.length)]};MochiKit.Random.shuffled=function(a){var b=a.length,c=Array(b);c[0]=a[0];for(var d=1;d<b-1;++d){var e=Math.floor(MochiKit.Random.random()*(d+1));c[d]=c[e];c[e]=a[d]}return c};
MochiKit.Random.sample=function(a,b){for(var c=a.length,d=Array(b),e={},f=0;f<b;++f){for(var g=MochiKit.Random.randRange(c);g in e;)g=MochiKit.Random.randRange(c);e[g]=true;d[f]=a[g]}return d};MochiKit.Random._IRndGenerator=function(){};MochiKit.Random._IRndGenerator.prototype.seed=function(){};MochiKit.Random._IRndGenerator.prototype.getState=function(){};MochiKit.Random._IRndGenerator.prototype.setState=function(){};MochiKit.Random._IRndGenerator.prototype.random=function(){};
MochiKit.Random.MersenneTwister=function(a){this._mt=new MochiKit._MersenneTwister19937;this.seed(a)};MochiKit.Random.MersenneTwister.prototype.seed=function(a){a=typeof a=="number"?a:(new Date).getTime();this._mt.init_genrand(a)};MochiKit.Random.MersenneTwister.prototype.getState=function(){return this._mt._getState()};MochiKit.Random.MersenneTwister.prototype.setState=function(a){this._mt._setState(a)};MochiKit.Random.MersenneTwister.prototype.random=function(){return this._mt.genrand_real2()};
MochiKit.Random.SystemRandom=function(){};MochiKit.Random.SystemRandom.prototype.seed=function(){};MochiKit.Random.SystemRandom.prototype.getState=function(){};MochiKit.Random.SystemRandom.prototype.setState=function(){};MochiKit.Random.SystemRandom.prototype.random=function(){return Math.random()};MochiKit.Random._generator=null;MochiKit.Random._setGenerator=function(a){MochiKit.Random._generator=a};MochiKit.Random.__new__=function(){MochiKit.Random._setGenerator(new MochiKit.Random.MersenneTwister)};
MochiKit.Random.__new__();MochiKit.Base._exportSymbols(this,MochiKit.Random);
